name: Terraform Destroy

on:
  workflow_dispatch: # Manual trigger from GitHub UI

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.6.0

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install zip, unzip & AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y zip unzip python3-pip
        pip3 install awscli --upgrade --user
        export PATH=$PATH:~/.local/bin

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Terraform Destroy
      run: terraform destroy -auto-approve